"""Curated word bank for word-of-the-day.

A static list instead of a live dictionary API: no external dependency to
fail, and the definitions/examples are hand-checked rather than scraped.
Deterministic daily selection (see pick_word.py) cycles through this list
without repeats until it's exhausted, then reshuffles for the next cycle.
"""

WORD_BANK = [
    {"word": "ephemeral", "pos": "adjective", "definition": "Lasting for a very short time.", "example": "The cherry blossoms' beauty is ephemeral, gone within a week."},
    {"word": "ubiquitous", "pos": "adjective", "definition": "Present, appearing, or found everywhere.", "example": "Smartphones have become ubiquitous in modern life."},
    {"word": "serendipity", "pos": "noun", "definition": "The occurrence of finding pleasant things by chance.", "example": "Meeting her old mentor at the airport was pure serendipity."},
    {"word": "mellifluous", "pos": "adjective", "definition": "Sweet or musical; pleasant to hear.", "example": "The narrator's mellifluous voice made the audiobook a pleasure."},
    {"word": "halcyon", "pos": "adjective", "definition": "Denoting a period of time that was idyllically happy and peaceful.", "example": "She often thought back to the halcyon days of college."},
    {"word": "ineffable", "pos": "adjective", "definition": "Too great or extreme to be expressed in words.", "example": "The view from the summit left them with an ineffable sense of awe."},
    {"word": "petrichor", "pos": "noun", "definition": "The pleasant, earthy smell after rain falls on dry ground.", "example": "The petrichor rising from the sidewalk was the first sign of the storm."},
    {"word": "luminous", "pos": "adjective", "definition": "Giving off light; bright or shining.", "example": "The jellyfish tank glowed with a luminous blue."},
    {"word": "quintessential", "pos": "adjective", "definition": "Representing the most perfect or typical example of a quality or type.", "example": "The small diner was the quintessential roadside stop."},
    {"word": "magnanimous", "pos": "adjective", "definition": "Generous or forgiving, especially toward a rival or someone less powerful.", "example": "The winning team was magnanimous in victory, praising their opponents."},
    {"word": "obfuscate", "pos": "verb", "definition": "To make something unclear or difficult to understand, often deliberately.", "example": "The report seemed designed to obfuscate rather than explain the losses."},
    {"word": "pernicious", "pos": "adjective", "definition": "Having a harmful effect, especially in a gradual or subtle way.", "example": "The pernicious rumor spread quietly through the office for weeks."},
    {"word": "ebullient", "pos": "adjective", "definition": "Cheerful and full of energy.", "example": "She gave an ebullient speech after hearing the good news."},
    {"word": "gregarious", "pos": "adjective", "definition": "Fond of company; sociable.", "example": "His gregarious personality made him the life of every party."},
    {"word": "laconic", "pos": "adjective", "definition": "Using very few words; concise to the point of terseness.", "example": "His laconic reply gave nothing away about his true feelings."},
    {"word": "sagacious", "pos": "adjective", "definition": "Having or showing keen mental discernment and good judgment.", "example": "The sagacious old judge saw through the witness's story immediately."},
    {"word": "verbose", "pos": "adjective", "definition": "Using more words than needed; wordy.", "example": "The instructions were so verbose that most people skipped them entirely."},
    {"word": "taciturn", "pos": "adjective", "definition": "Reserved or uncommunicative in speech; saying little.", "example": "The taciturn farmer answered every question with a single word."},
    {"word": "ostentatious", "pos": "adjective", "definition": "Designed to impress or attract notice; showy.", "example": "The mansion's gold gates felt ostentatious next to the modest neighborhood."},
    {"word": "assiduous", "pos": "adjective", "definition": "Showing great care and perseverance in one's work.", "example": "Her assiduous note-taking paid off when exam season arrived."},
    {"word": "cognizant", "pos": "adjective", "definition": "Having knowledge or awareness of something.", "example": "He was fully cognizant of the risks before signing the contract."},
    {"word": "deference", "pos": "noun", "definition": "Respectful submission or yielding to the judgment of another.", "example": "The junior engineer spoke with deference to the project lead."},
    {"word": "exacerbate", "pos": "verb", "definition": "To make a problem or situation worse.", "example": "Skipping meals only exacerbated her afternoon headaches."},
    {"word": "fastidious", "pos": "adjective", "definition": "Very attentive to accuracy and detail; hard to please.", "example": "The fastidious editor caught every misplaced comma."},
    {"word": "garrulous", "pos": "adjective", "definition": "Excessively talkative, especially about trivial matters.", "example": "The garrulous cab driver talked the entire ride without pausing."},
    {"word": "hackneyed", "pos": "adjective", "definition": "Lacking originality or freshness; overused.", "example": "The movie leaned on hackneyed plot twists we'd all seen before."},
    {"word": "idiosyncratic", "pos": "adjective", "definition": "Peculiar or individual to a particular person; distinctive.", "example": "His idiosyncratic filing system made sense only to him."},
    {"word": "juxtaposition", "pos": "noun", "definition": "The fact of placing two things close together for contrasting effect.", "example": "The photo's juxtaposition of old ruins and new skyscrapers was striking."},
    {"word": "labyrinthine", "pos": "adjective", "definition": "Extremely complex or tangled, like a maze.", "example": "Navigating the labyrinthine tax code required a specialist."},
    {"word": "meticulous", "pos": "adjective", "definition": "Showing great attention to detail; very careful and precise.", "example": "The meticulous chef measured every ingredient to the gram."},
    {"word": "nebulous", "pos": "adjective", "definition": "Unclear, vague, or ill-defined.", "example": "The proposal's goals were too nebulous to act on."},
    {"word": "obstinate", "pos": "adjective", "definition": "Stubbornly refusing to change one's opinion or approach.", "example": "The obstinate toddler refused to leave the playground."},
    {"word": "panacea", "pos": "noun", "definition": "A solution or remedy for all difficulties or diseases.", "example": "More funding alone is no panacea for the school's problems."},
    {"word": "quixotic", "pos": "adjective", "definition": "Extremely idealistic and unrealistic, often impractically so.", "example": "His quixotic plan to sail solo around the world worried his family."},
    {"word": "ravenous", "pos": "adjective", "definition": "Extremely hungry.", "example": "After the hike, they were ravenous and ate everything in sight."},
    {"word": "sanguine", "pos": "adjective", "definition": "Optimistic or positive, especially in a difficult situation.", "example": "Despite the setback, she remained sanguine about the project's future."},
    {"word": "tenacious", "pos": "adjective", "definition": "Holding firmly to something; persistent.", "example": "The tenacious reporter kept calling until someone answered her questions."},
    {"word": "umbrage", "pos": "noun", "definition": "Offense or annoyance.", "example": "He took umbrage at being left off the invitation list."},
    {"word": "vociferous", "pos": "adjective", "definition": "Expressing opinions or feelings in a loud and forceful way.", "example": "A vociferous group of fans protested the ticket price hike."},
    {"word": "whimsical", "pos": "adjective", "definition": "Playfully quaint or fanciful, especially in an appealing way.", "example": "The children's book was full of whimsical illustrations."},
    {"word": "yearning", "pos": "noun", "definition": "A deep, wistful desire, especially for something out of reach.", "example": "She felt a quiet yearning for the town she'd grown up in."},
    {"word": "zealous", "pos": "adjective", "definition": "Having or showing great energy or enthusiasm for a cause.", "example": "The zealous volunteers arrived before sunrise to set up the shelter."},
    {"word": "abrogate", "pos": "verb", "definition": "To repeal or do away with a law, right, or agreement.", "example": "The new government moved to abrogate the previous trade deal."},
    {"word": "benevolent", "pos": "adjective", "definition": "Kind and generous; well-meaning.", "example": "A benevolent donor covered the shelter's entire winter budget."},
    {"word": "capricious", "pos": "adjective", "definition": "Given to sudden and unaccountable changes of mood or behavior.", "example": "The capricious weather turned a sunny hike into a downpour."},
    {"word": "dogmatic", "pos": "adjective", "definition": "Inclined to lay down principles as incontrovertibly true, without allowing debate.", "example": "He was so dogmatic about his diet that he refused to hear any counterargument."},
    {"word": "effervescent", "pos": "adjective", "definition": "Vivacious and enthusiastic; also, bubbling.", "example": "Her effervescent energy lifted the mood of the whole meeting."},
    {"word": "fortuitous", "pos": "adjective", "definition": "Happening by a lucky chance; fortunate.", "example": "Their fortuitous meeting on the train led to a decade-long friendship."},
    {"word": "gratuitous", "pos": "adjective", "definition": "Uncalled for; lacking good reason; unwarranted.", "example": "Critics called the film's violence gratuitous and unnecessary to the plot."},
    {"word": "hyperbole", "pos": "noun", "definition": "Exaggerated statements not meant to be taken literally.", "example": "Saying he waited a million years for the bus was obvious hyperbole."},
    {"word": "impetuous", "pos": "adjective", "definition": "Acting quickly without thought or care.", "example": "His impetuous decision to quit surprised everyone at the firm."},
    {"word": "jubilant", "pos": "adjective", "definition": "Feeling or expressing great happiness and triumph.", "example": "The jubilant crowd sang long after the final whistle."},
    {"word": "lethargic", "pos": "adjective", "definition": "Sluggish and lacking energy.", "example": "The heat made everyone lethargic by mid-afternoon."},
    {"word": "malleable", "pos": "adjective", "definition": "Easily influenced or shaped; able to be pressed into shape.", "example": "Young minds are often more malleable than we give them credit for."},
    {"word": "nostalgia", "pos": "noun", "definition": "A sentimental longing for the past.", "example": "The song filled her with nostalgia for summers at the lake house."},
    {"word": "opulent", "pos": "adjective", "definition": "Ostentatiously rich and luxurious.", "example": "The hotel lobby was opulent, all marble and gold trim."},
    {"word": "paradox", "pos": "noun", "definition": "A statement or situation that seems contradictory but may reveal a truth.", "example": "It's a paradox that the more choices we have, the harder deciding becomes."},
    {"word": "quagmire", "pos": "noun", "definition": "A difficult, complex situation from which it's hard to escape.", "example": "The merger turned into a legal quagmire that lasted three years."},
    {"word": "resplendent", "pos": "adjective", "definition": "Attractive and impressive through being richly colorful or sumptuous.", "example": "The peacock stood resplendent in the morning sun."},
    {"word": "stoic", "pos": "adjective", "definition": "Enduring pain or hardship without showing feelings or complaint.", "example": "She remained stoic through the entire diagnosis and treatment."},
    {"word": "tumultuous", "pos": "adjective", "definition": "Marked by disorder, confusion, or loud commotion.", "example": "The band walked off to a tumultuous ovation."},
    {"word": "unassuming", "pos": "adjective", "definition": "Not pretentious or arrogant; modest.", "example": "The unassuming scientist rarely mentioned her own Nobel Prize."},
    {"word": "vivacious", "pos": "adjective", "definition": "Attractively lively and animated.", "example": "Her vivacious storytelling kept the whole table laughing."},
    {"word": "wistful", "pos": "adjective", "definition": "Having a feeling of vague or regretful longing.", "example": "He gave a wistful smile as he packed up his childhood bedroom."},
    {"word": "extraneous", "pos": "adjective", "definition": "Irrelevant or unrelated to the subject at hand.", "example": "The editor cut every extraneous detail from the article."},
    {"word": "facetious", "pos": "adjective", "definition": "Treating serious issues with deliberately inappropriate humor.", "example": "His facetious remark didn't land well in the safety briefing."},
    {"word": "harbinger", "pos": "noun", "definition": "A person or thing that signals the approach of something.", "example": "The first robin is often seen as a harbinger of spring."},
    {"word": "incongruous", "pos": "adjective", "definition": "Not in harmony or keeping with the surroundings or context.", "example": "The skate park looked incongruous next to the old stone cathedral."},
    {"word": "jovial", "pos": "adjective", "definition": "Cheerful and friendly.", "example": "The jovial host greeted every guest by name."},
    {"word": "lucid", "pos": "adjective", "definition": "Expressed clearly; easy to understand.", "example": "Her lucid explanation cleared up months of confusion."},
    {"word": "mundane", "pos": "adjective", "definition": "Lacking interest or excitement; commonplace.", "example": "Even mundane errands felt lighter with good company."},
    {"word": "nonchalant", "pos": "adjective", "definition": "Feeling or appearing casually calm and unconcerned.", "example": "He stayed nonchalant even as the deadline crept closer."},
    {"word": "ostracize", "pos": "verb", "definition": "To exclude someone from a society or group.", "example": "The whistleblower was quietly ostracized by former colleagues."},
    {"word": "paradigm", "pos": "noun", "definition": "A typical example or pattern of something; a model.", "example": "The discovery shifted the entire paradigm of the field."},
    {"word": "quell", "pos": "verb", "definition": "To put an end to a rebellion or violent situation; to suppress a feeling.", "example": "The announcement did little to quell the growing anxiety."},
    {"word": "staunch", "pos": "adjective", "definition": "Loyal and committed in attitude; steadfast.", "example": "She remained a staunch supporter of the local library through every budget cut."},
    {"word": "transient", "pos": "adjective", "definition": "Lasting only for a short time; passing through.", "example": "The town's population swells each summer with transient workers."},
    {"word": "unequivocal", "pos": "adjective", "definition": "Leaving no doubt; unambiguous.", "example": "The board gave an unequivocal yes to the new proposal."},
    {"word": "vex", "pos": "verb", "definition": "To cause annoyance or worry to someone.", "example": "The riddle vexed the students for the rest of the afternoon."},
    {"word": "winsome", "pos": "adjective", "definition": "Attractive or appealing in a charming, innocent way.", "example": "The puppy's winsome expression won over the entire office."},
    {"word": "abstruse", "pos": "adjective", "definition": "Difficult to understand; obscure.", "example": "The lecture's abstruse math lost half the room in five minutes."},
    {"word": "brevity", "pos": "noun", "definition": "Concise and exact use of words.", "example": "The eulogy's brevity made it more powerful, not less."},
    {"word": "candid", "pos": "adjective", "definition": "Truthful and straightforward; frank.", "example": "She gave a candid account of what had gone wrong."},
    {"word": "diligent", "pos": "adjective", "definition": "Having or showing care and conscientiousness in one's work.", "example": "The diligent intern double-checked every figure before submitting."},
    {"word": "enigma", "pos": "noun", "definition": "A person or thing that is mysterious or difficult to understand.", "example": "The old house's history remained an enigma to the whole town."},
    {"word": "flippant", "pos": "adjective", "definition": "Not showing serious or respectful feeling; casually disrespectful.", "example": "His flippant response to the complaint made things worse."},
    {"word": "gullible", "pos": "adjective", "definition": "Easily persuaded to believe something; credulous.", "example": "The prank only worked because his roommate was so gullible."},
    {"word": "hapless", "pos": "adjective", "definition": "Unfortunate; luckless.", "example": "The hapless intern hit reply-all on the wrong email."},
    {"word": "impervious", "pos": "adjective", "definition": "Unable to be affected by something; not allowing passage.", "example": "He seemed impervious to criticism no matter how sharp."},
    {"word": "jaded", "pos": "adjective", "definition": "Tired, bored, or lacking enthusiasm, typically after too much of something.", "example": "Years of red-eye flights left her jaded about business travel."},
    {"word": "kudos", "pos": "noun", "definition": "Praise and honor received for an achievement.", "example": "Kudos to the whole team for shipping ahead of schedule."},
    {"word": "lament", "pos": "verb", "definition": "To express sorrow or regret about something.", "example": "Longtime fans lamented the stadium's closing."},
    {"word": "morose", "pos": "adjective", "definition": "Sullen and ill-tempered.", "example": "He'd been morose ever since the trip was cancelled."},
    {"word": "nadir", "pos": "noun", "definition": "The lowest or most unsuccessful point of a situation.", "example": "Losing the championship game was the nadir of his coaching career."},
    {"word": "oblivious", "pos": "adjective", "definition": "Not aware of or concerned about what is happening.", "example": "He walked past the crowd, oblivious to the commotion."},
    {"word": "placate", "pos": "verb", "definition": "To make someone less angry or hostile.", "example": "The airline offered vouchers to placate the delayed passengers."},
    {"word": "quandary", "pos": "noun", "definition": "A state of uncertainty over what to do in a difficult situation.", "example": "She was in a quandary over which offer to accept."},
    {"word": "rancor", "pos": "noun", "definition": "Bitterness or resentfulness, especially long-lasting.", "example": "Years later, there was still rancor between the two former partners."},
    {"word": "solace", "pos": "noun", "definition": "Comfort in a time of distress or sadness.", "example": "She found solace in long walks after the move."},
    {"word": "tangible", "pos": "adjective", "definition": "Perceptible by touch; clear and definite.", "example": "The renovation finally produced tangible results everyone could see."},
    {"word": "undermine", "pos": "verb", "definition": "To weaken or damage something gradually.", "example": "Constant interruptions undermined the team's confidence."},
    {"word": "vindicate", "pos": "verb", "definition": "To clear someone of blame or suspicion; to justify.", "example": "New evidence eventually vindicated the wrongly accused clerk."},
    {"word": "wary", "pos": "adjective", "definition": "Feeling or showing caution about possible dangers or problems.", "example": "She stayed wary of any deal that sounded too good."},
    {"word": "zeitgeist", "pos": "noun", "definition": "The defining spirit or mood of a particular period.", "example": "The film captured the zeitgeist of the early internet era."},
    {"word": "amiable", "pos": "adjective", "definition": "Having a friendly and pleasant manner.", "example": "The amiable shopkeeper remembered every regular customer's name."},
    {"word": "brazen", "pos": "adjective", "definition": "Bold and without shame.", "example": "The brazen theft happened in broad daylight."},
    {"word": "conundrum", "pos": "noun", "definition": "A confusing and difficult problem or question.", "example": "Balancing growth with quality remained the startup's central conundrum."},
    {"word": "discord", "pos": "noun", "definition": "Disagreement or conflict between people.", "example": "The inheritance sparked years of discord in the family."},
    {"word": "elated", "pos": "adjective", "definition": "Extremely happy and excited.", "example": "She was elated when the acceptance letter finally arrived."},
    {"word": "frugal", "pos": "adjective", "definition": "Sparing or economical with money or resources.", "example": "His frugal habits let him retire a decade early."},
    {"word": "gravitas", "pos": "noun", "definition": "Dignity, seriousness, or solemnity of manner.", "example": "The retired general spoke with a gravitas the room couldn't ignore."},
    {"word": "hedonist", "pos": "noun", "definition": "A person who believes pleasure is the most important pursuit in life.", "example": "His friends teased him as a hedonist for planning vacations around food."},
    {"word": "imminent", "pos": "adjective", "definition": "About to happen very soon.", "example": "Forecasters warned that the storm's landfall was imminent."},
    {"word": "jargon", "pos": "noun", "definition": "Special words or expressions used by a particular profession or group.", "example": "The contract was so full of legal jargon that no one could parse it."},
    {"word": "lampoon", "pos": "verb", "definition": "To publicly criticize someone or something using ridicule or satire.", "example": "The sketch show loved to lampoon the week's political news."},
    {"word": "myriad", "pos": "adjective", "definition": "A countless or extremely great number of.", "example": "The city offered myriad ways to spend a rainy afternoon."},
    {"word": "notorious", "pos": "adjective", "definition": "Famous or well known, typically for something bad.", "example": "The intersection was notorious for fender-benders."},
    {"word": "obsolete", "pos": "adjective", "definition": "No longer produced or used; out of date.", "example": "The old software became obsolete after the last update."},
    {"word": "plausible", "pos": "adjective", "definition": "Seeming reasonable or probable.", "example": "His explanation was plausible enough that no one pressed further."},
    {"word": "rhetoric", "pos": "noun", "definition": "Language designed to persuade, sometimes with less regard for substance.", "example": "Voters grew tired of rhetoric and wanted specific plans."},
    {"word": "stagnant", "pos": "adjective", "definition": "Showing no activity; not flowing or developing.", "example": "Wages in the sector had been stagnant for a decade."},
    {"word": "thwart", "pos": "verb", "definition": "To prevent someone from accomplishing something.", "example": "Heavy rain thwarted their plans for an outdoor wedding."},
    {"word": "unbridled", "pos": "adjective", "definition": "Uncontrolled; unrestrained.", "example": "The kids ran across the field with unbridled joy."},
    {"word": "vantage", "pos": "noun", "definition": "A place or position giving a good view or advantage.", "example": "From their vantage on the hill, they could see the whole valley."},
    {"word": "wither", "pos": "verb", "definition": "To become dry and shriveled, or to lose strength or vitality.", "example": "Without rain for weeks, the garden began to wither."},
    {"word": "adversity", "pos": "noun", "definition": "Difficult or unfavorable circumstances.", "example": "Their friendship was forged through years of shared adversity."},
    {"word": "bolster", "pos": "verb", "definition": "To support or strengthen something.", "example": "The new hires helped bolster the team's design capacity."},
    {"word": "congenial", "pos": "adjective", "definition": "Pleasant or agreeable, especially in creating a friendly atmosphere.", "example": "The office had a congenial, low-drama atmosphere."},
    {"word": "deft", "pos": "adjective", "definition": "Neatly skillful and quick in one's movements or actions.", "example": "With a few deft strokes, she fixed the typo no one else caught."},
    {"word": "elusive", "pos": "adjective", "definition": "Difficult to find, catch, or achieve.", "example": "A good night's sleep felt elusive during finals week."},
    {"word": "fervent", "pos": "adjective", "definition": "Having or displaying passionate intensity.", "example": "She was a fervent advocate for the new bike lanes."},
    {"word": "gauche", "pos": "adjective", "definition": "Lacking social grace; awkward or tactless.", "example": "Asking about her salary at dinner was pretty gauche."},
    {"word": "harmony", "pos": "noun", "definition": "Agreement or concord; a pleasing combination of elements.", "example": "The old and new wings of the museum sat in surprising harmony."},
    {"word": "impasse", "pos": "noun", "definition": "A situation in which no progress is possible; deadlock.", "example": "Negotiations reached an impasse after the third round of talks."},
    {"word": "jeopardy", "pos": "noun", "definition": "Danger of loss, harm, or failure.", "example": "The delayed shipment put the entire launch in jeopardy."},
    {"word": "kaleidoscope", "pos": "noun", "definition": "A constantly changing pattern or sequence of elements.", "example": "The market was a kaleidoscope of colors, smells, and languages."},
    {"word": "lavish", "pos": "adjective", "definition": "Sumptuously rich, elaborate, or luxurious.", "example": "They threw a lavish party to celebrate the anniversary."},
    {"word": "meander", "pos": "verb", "definition": "To follow a winding course; to wander without a fixed direction.", "example": "The trail meanders along the river for nearly ten miles."},
    {"word": "nuance", "pos": "noun", "definition": "A subtle difference in meaning, expression, or feeling.", "example": "The translator worked hard to preserve the poem's every nuance."},
    {"word": "obscure", "pos": "adjective", "definition": "Not well known; hard to see or understand.", "example": "The bookstore specialized in obscure and out-of-print titles."},
    {"word": "pragmatic", "pos": "adjective", "definition": "Dealing with things sensibly and realistically.", "example": "Her pragmatic approach cut the project timeline in half."},
    {"word": "quiver", "pos": "verb", "definition": "To shake with a slight rapid motion; to tremble.", "example": "His voice began to quiver as he finished the toast."},
    {"word": "resolute", "pos": "adjective", "definition": "Admirably purposeful and determined; unwavering.", "example": "She stayed resolute even as the criticism piled up."},
    {"word": "subtle", "pos": "adjective", "definition": "So delicate or precise as to be difficult to detect or describe.", "example": "There was a subtle shift in his tone once the offer came up."},
    {"word": "trepidation", "pos": "noun", "definition": "A feeling of fear or anxiety about something that may happen.", "example": "She approached the interview with more trepidation than usual."},
    {"word": "unfathomable", "pos": "adjective", "definition": "Impossible to understand or make sense of; incomprehensible.", "example": "The scale of the ancient ruins felt almost unfathomable."},
    {"word": "valor", "pos": "noun", "definition": "Great courage in the face of danger.", "example": "The firefighters were honored for their valor during the blaze."},
    {"word": "whim", "pos": "noun", "definition": "A sudden desire or impulse.", "example": "On a whim, they booked flights for the following weekend."},
    {"word": "zenith", "pos": "noun", "definition": "The time at which something is most powerful or successful.", "example": "The band's fame reached its zenith in the late nineties."},
    {"word": "acumen", "pos": "noun", "definition": "The ability to make good judgments and quick decisions.", "example": "Her business acumen turned the small shop into a regional chain."},
    {"word": "banal", "pos": "adjective", "definition": "So lacking in originality as to be obvious and boring.", "example": "The speech was full of banal advice everyone had heard before."},
    {"word": "cynical", "pos": "adjective", "definition": "Believing that people are motivated by self-interest; distrustful.", "example": "Years in politics had made him cynical about campaign promises."},
    {"word": "disdain", "pos": "noun", "definition": "A feeling that someone or something is unworthy of respect.", "example": "She viewed the shortcut with open disdain."},
    {"word": "eloquent", "pos": "adjective", "definition": "Fluent and persuasive in speaking or writing.", "example": "His eloquent closing argument swayed the jury."},
    {"word": "frivolous", "pos": "adjective", "definition": "Not having any serious purpose or value.", "example": "The lawsuit was dismissed as frivolous."},
    {"word": "grievance", "pos": "noun", "definition": "A real or imagined wrong causing resentment.", "example": "Employees filed a formal grievance over the schedule change."},
    {"word": "hindrance", "pos": "noun", "definition": "A thing that hinders or gets in the way of progress.", "example": "The broken elevator was a real hindrance during move-in week."},
    {"word": "inertia", "pos": "noun", "definition": "A tendency to remain unchanged; resistance to motion or change.", "example": "Organizational inertia kept the old process alive long after it made sense."},
    {"word": "jocular", "pos": "adjective", "definition": "Fond of joking; humorous or playful.", "example": "His jocular tone put the nervous new hires at ease."},
    {"word": "knack", "pos": "noun", "definition": "An acquired or natural skill at doing something well.", "example": "She had a real knack for calming down upset customers."},
    {"word": "listless", "pos": "adjective", "definition": "Lacking energy or enthusiasm.", "example": "The whole class felt listless after the long holiday weekend."},
    {"word": "mirth", "pos": "noun", "definition": "Amusement, especially expressed through laughter.", "example": "The blooper reel was met with unrestrained mirth."},
    {"word": "novice", "pos": "noun", "definition": "A person new to and inexperienced in a job or situation.", "example": "As a novice sailor, he stuck close to shore."},
    {"word": "ornate", "pos": "adjective", "definition": "Made in an elaborate, decorated style.", "example": "The ceiling was covered in ornate hand-painted molding."},
    {"word": "pensive", "pos": "adjective", "definition": "Engaged in or reflecting deep or serious thought.", "example": "He stared out the train window, pensive and quiet."},
    {"word": "querulous", "pos": "adjective", "definition": "Complaining in a petulant or whining manner.", "example": "The querulous customer had an objection to every suggestion."},
    {"word": "robust", "pos": "adjective", "definition": "Strong and healthy; vigorous, or able to withstand adverse conditions.", "example": "The bridge's robust design survived the record flood."},
    {"word": "scrupulous", "pos": "adjective", "definition": "Diligent, thorough, and extremely attentive to detail or correctness.", "example": "The auditor was scrupulous about matching every receipt."},
    {"word": "tedious", "pos": "adjective", "definition": "Too long, slow, or dull; tiresome or monotonous.", "example": "Filing the paperwork was tedious but necessary."},
    {"word": "vicarious", "pos": "adjective", "definition": "Experienced through the feelings or actions of another person.", "example": "She got a vicarious thrill from her daughter's travel photos."},
    {"word": "wane", "pos": "verb", "definition": "To decrease in strength, intensity, or extent.", "example": "Public interest in the story began to wane after a few weeks."},
    {"word": "abate", "pos": "verb", "definition": "To become less intense or widespread.", "example": "The storm finally began to abate just after midnight."},
    {"word": "boisterous", "pos": "adjective", "definition": "Noisy, energetic, and cheerful.", "example": "The boisterous crowd spilled out onto the street after the game."},
    {"word": "contrite", "pos": "adjective", "definition": "Feeling or expressing remorse for a wrong committed.", "example": "He offered a contrite apology the morning after."},
    {"word": "dismal", "pos": "adjective", "definition": "Depressing or dreary; very bad.", "example": "The team's dismal record cost the coach his job."},
    {"word": "exuberant", "pos": "adjective", "definition": "Filled with lively energy and excitement.", "example": "The kids gave an exuberant welcome to their returning father."},
    {"word": "feasible", "pos": "adjective", "definition": "Possible to do easily or conveniently; practicable.", "example": "The engineers confirmed the design was structurally feasible."},
    {"word": "haphazard", "pos": "adjective", "definition": "Lacking any obvious organizing principle; random.", "example": "The files were stored in a haphazard mix of folders and formats."},
    {"word": "incessant", "pos": "adjective", "definition": "Continuing without pause or interruption.", "example": "The incessant construction noise made it hard to concentrate."},
    {"word": "keepsake", "pos": "noun", "definition": "An item kept in memory of the person who gave it or of an event.", "example": "She kept the ticket stub as a keepsake from their first concert."},
    {"word": "languid", "pos": "adjective", "definition": "Displaying or having a disinclination for physical exertion; slow and relaxed.", "example": "They spent a languid Sunday reading on the porch."},
    {"word": "nonsensical", "pos": "adjective", "definition": "Having no meaning; absurd.", "example": "The instructions were so nonsensical that no one could assemble the shelf."},
    {"word": "ominous", "pos": "adjective", "definition": "Giving the impression that something bad is about to happen.", "example": "Dark clouds gathered with an ominous silence over the field."},
    {"word": "perplex", "pos": "verb", "definition": "To confuse or puzzle someone.", "example": "The riddle continued to perplex even the sharpest students."},
    {"word": "quibble", "pos": "verb", "definition": "To argue or complain about a trivial matter.", "example": "They quibbled over the exact wording for nearly an hour."},
    {"word": "reticent", "pos": "adjective", "definition": "Not revealing one's thoughts or feelings readily; reserved.", "example": "He was reticent about the details of his old job."},
    {"word": "stalwart", "pos": "adjective", "definition": "Loyal, reliable, and hardworking.", "example": "A stalwart group of volunteers showed up every single Saturday."},
    {"word": "tenuous", "pos": "adjective", "definition": "Very weak or slight; barely sufficient.", "example": "The evidence linking the two events was tenuous at best."},
    {"word": "unwavering", "pos": "adjective", "definition": "Steady or resolute; not wavering.", "example": "Her unwavering focus got the project across the finish line."},
    {"word": "vestige", "pos": "noun", "definition": "A trace or remaining sign of something that once existed.", "example": "The old rail line is the last vestige of the town's industrial past."},
    {"word": "wry", "pos": "adjective", "definition": "Using or expressing dry, mocking humor.", "example": "She gave a wry smile at the irony of the situation."},
    {"word": "abhor", "pos": "verb", "definition": "To regard with disgust and hatred.", "example": "He openly abhorred cutting corners on safety."},
    {"word": "buoyant", "pos": "adjective", "definition": "Cheerful and optimistic; able to float.", "example": "The team stayed buoyant even after the early setback."},
    {"word": "cordial", "pos": "adjective", "definition": "Warm and friendly.", "example": "Relations between the two offices remained cordial despite the merger."},
    {"word": "demure", "pos": "adjective", "definition": "Reserved, modest, and shy, especially in a deliberate way.", "example": "She gave a demure nod and slipped out of the spotlight."},
    {"word": "exacting", "pos": "adjective", "definition": "Making great demands on one's skill, attention, or other resources.", "example": "The exacting client rejected three drafts before approving one."},
    {"word": "fickle", "pos": "adjective", "definition": "Changing frequently, especially regarding loyalties or affections.", "example": "Public opinion on the policy proved fickle within a single news cycle."},
    {"word": "gaudy", "pos": "adjective", "definition": "Extravagantly bright or showy, in a tasteless way.", "example": "The gaudy neon sign clashed with the quiet street around it."},
    {"word": "hallowed", "pos": "adjective", "definition": "Greatly revered or respected; sacred.", "example": "The old library was hallowed ground for generations of students."},
    {"word": "indolent", "pos": "adjective", "definition": "Wanting to avoid activity or exertion; lazy.", "example": "The cat spent the whole afternoon in indolent stillness on the windowsill."},
    {"word": "jocund", "pos": "adjective", "definition": "Cheerful and lighthearted.", "example": "The jocund innkeeper welcomed every guest like an old friend."},
    {"word": "lucrative", "pos": "adjective", "definition": "Producing a great deal of profit.", "example": "The side project turned into a surprisingly lucrative business."},
    {"word": "meager", "pos": "adjective", "definition": "Lacking in quantity or quality; scanty.", "example": "The startup ran for a year on a meager budget."},
    {"word": "obdurate", "pos": "adjective", "definition": "Stubbornly refusing to change one's opinion or course of action.", "example": "He remained obdurate despite the committee's repeated appeals."},
    {"word": "pithy", "pos": "adjective", "definition": "Concise and forcefully expressive.", "example": "Her pithy summary said more in one line than the full report."},
    {"word": "quaint", "pos": "adjective", "definition": "Attractively unusual or old-fashioned.", "example": "The quaint village square hadn't changed in a century."},
    {"word": "rambunctious", "pos": "adjective", "definition": "Uncontrollably exuberant or boisterous.", "example": "The rambunctious puppy tore through the living room."},
    {"word": "serene", "pos": "adjective", "definition": "Calm, peaceful, and untroubled.", "example": "The lake was perfectly serene at dawn."},
    {"word": "tactful", "pos": "adjective", "definition": "Having or showing skill and sensitivity in dealing with others.", "example": "She found a tactful way to decline without offending anyone."},
    {"word": "unassailable", "pos": "adjective", "definition": "Unable to be attacked, questioned, or defeated.", "example": "His alibi was unassailable once the security footage surfaced."},
    {"word": "whimsy", "pos": "noun", "definition": "Playfully quaint or fanciful behavior or humor.", "example": "The shop's window displays were full of unexpected whimsy."},
    {"word": "zealot", "pos": "noun", "definition": "A person who is fanatical and uncompromising about a cause.", "example": "He was no zealot, just someone who cared deeply about clean water."},
]
